<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Brians-MacBook-Pro.local" name="com.l1.interop.USSDFunctionalTest" tests="10" failures="0" timestamp="1 Mar 2017 16:18:13 GMT" time="5.795" errors="1">
  <testcase name="get_ussd_createuser1" time="0.279" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="1.891" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="0.309" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="0.251" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="0.289" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="0.288" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="0.253" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="0.272" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="0.368" classname="com.l1.interop.USSDFunctionalTest"/>
  <testcase name="get_ussd_createuser1" time="1.595" classname="com.l1.interop.USSDFunctionalTest">
    <error type="java.lang.AssertionError" message="
Expected: not a string containing &quot;Wrong Input&quot;
     but: was &quot;&lt;UssdResponse version=\&quot;1.0\&quot;&gt;\n  &lt;Status code=\&quot;0\&quot;/&gt;\n  &lt;Message&gt;Wrong Input \n\n0. Home\n1. Back&lt;/Message&gt;\n  &lt;DefaultCode&gt;*123#&lt;/DefaultCode&gt;\n  &lt;PhoneNumber/&gt;\n&lt;/UssdResponse&gt;&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: not a string containing "Wrong Input"
     but: was "<UssdResponse version=\"1.0\">\n  <Status code=\"0\"/>\n  <Message>Wrong Input \n\n0. Home\n1. Back</Message>\n  <DefaultCode>*123#</DefaultCode>\n  <PhoneNumber/>\n</UssdResponse>"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.l1.interop.USSDFunctionalTest.get_ussd_createuser1(USSDFunctionalTest.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- get_ussd_createuser1 -->
</testsuite> <!-- com.l1.interop.USSDFunctionalTest -->
